/*
 * Tribufu API
 *
 * API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.4.3
 * Contact: contact@tribufu.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApplicationType {
    #[serde(rename = "software")]
    Software,
    #[serde(rename = "game")]
    Game,

}

impl std::fmt::Display for ApplicationType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Software => write!(f, "software"),
            Self::Game => write!(f, "game"),
        }
    }
}

impl Default for ApplicationType {
    fn default() -> ApplicationType {
        Self::Software
    }
}

