/*
 * Tribufu API
 *
 * API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: contact@tribufu.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HashViewModel {
    #[serde(rename = "value", deserialize_with = "Option::deserialize")]
    pub value: Option<String>,
}

impl HashViewModel {
    pub fn new(value: Option<String>) -> HashViewModel {
        HashViewModel {
            value,
        }
    }
}

