/*
 * Tribufu API
 *
 * API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: contact@tribufu.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntrospectRequest {
    #[serde(rename = "token", deserialize_with = "Option::deserialize")]
    pub token: Option<String>,
    #[serde(rename = "token_type_hint")]
    pub token_type_hint: models::TokenHintType,
}

impl IntrospectRequest {
    pub fn new(token: Option<String>, token_type_hint: models::TokenHintType) -> IntrospectRequest {
        IntrospectRequest {
            token,
            token_type_hint,
        }
    }
}

