/*
 * Tribufu API
 *
 * API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: contact@tribufu.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateProfile {
    #[serde(rename = "display_name", deserialize_with = "Option::deserialize")]
    pub display_name: Option<String>,
    #[serde(rename = "biography", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub biography: Option<Option<String>>,
}

impl UpdateProfile {
    pub fn new(display_name: Option<String>) -> UpdateProfile {
        UpdateProfile {
            display_name,
            biography: None,
        }
    }
}

